In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('files_/final_clean.csv', index_col= 0, low_memory=False)

In [22]:

bins = [-1, 0, 31, 62, 92, 123, 153, 184, 214, 245, 275, 306, 336, 366]
labels = ['Ningún mes', 'Mes 1', 'Mes 2', 'Mes 3', 'Mes 4', 'Mes 5', 'Mes 6', 'Mes 7', 'Mes 8', 'Mes 9', 'Mes 10', 'Mes 11', 'Mes 12']

df['lead_time_group'] = pd.cut(df['lead_time'], bins=bins, labels=labels)
grouped = df[df['country'] == 'DEU'].groupby(['lead_time_group', 'canceled']).size().unstack(fill_value=0)
grouped['total_reservas'] = grouped.sum(axis=1)
grouped['porcentaje_cancelados'] = (grouped['True'] / grouped['total_reservas']) * 100
grouped['country'] = 'DEU'
grouped['lead_period'] = grouped.index
grouped=grouped.drop(columns=['False', 'True'])
DEU = grouped

In [16]:
PRT

canceled         total_reservas  porcentaje_cancelados country lead_period
lead_time_group
Ningún mes                 2043               9.348997     PRT  Ningún mes
Mes 1                      7273              27.320225     PRT       Mes 1
Mes 2                      3029              58.005943     PRT       Mes 2
Mes 3                      2317              65.472594     PRT       Mes 3
Mes 4                      2001              70.864568     PRT       Mes 4
Mes 5                      1549              69.205939     PRT       Mes 5
Mes 6                      1589              72.309629     PRT       Mes 6
Mes 7                      1086              72.744015     PRT       Mes 7
Mes 8                       754              85.809019     PRT       Mes 8
Mes 9                       836              75.956938     PRT       Mes 9
Mes 10                     1027              95.034080     PRT      Mes 10
Mes 11                      728              91.071429     PRT      Mes 11
Mes 12                      539              92.578850     PRT      Mes 12

In [24]:
df2 = pd.concat([GBR,PRT,ITA,ESP,IRL,FRA,DEU], axis=0)

In [25]:
df2.to_csv('files_/porcentajes_cancelaciones.csv', index=False)

In [3]:
df = pd.read_csv('files_/porcentajes_cancelaciones.csv', index_col= 0, low_memory=False)

In [9]:
df_ordenado = df.sort_values(by='porcentaje_cancelados', ascending=False)
df_ordenado.head(10)

                      country lead_period
porcentaje_cancelados
95.0                      PRT      Mes 10
93.0                      PRT      Mes 12
91.0                      PRT      Mes 11
86.0                      PRT       Mes 8
76.0                      PRT       Mes 9
75.0                      ESP      Mes 12
73.0                      PRT       Mes 7
72.0                      PRT       Mes 6
71.0                      ESP       Mes 9
71.0                      PRT       Mes 4